### ISSUE TITLE
Crash in game

### ISSUE THREAD

**Issue by samo79** [AmigaPorts/devilutionX#29]
Tested the OS4 native version compiled by Kas1e and everything works so far without big issue
However there is atleast a noticiable crash in game

[Crashlog_devilutionx_2019-08-20_16-37-04.txt](https://github.com/AmigaPorts/devilutionX/files/3521729/Crashlog_devilutionx_2019-08-20_16-37-04.txt)

**Comment by MBeijer** [comment]
This log doesn't say me anything. Is there a console log? Where did it crash?

**Comment by samo79** [comment]
I got the crash in the very first level, just moving my warrior around.
Next time I will try to replicate the issue catching the console log ..

**Comment by MBeijer** [comment]
Ah, yeah, sometimes that happens. I think it's some pointer that goes out of bounds. The same issue applies to 68k and PPC-BE Linux as well.

**Comment by kas1e** [comment]
@MBeijer
> Ah, yeah, sometimes that happens. I think it's some pointer that goes out of bounds. 

Yeah you are right, DAR regist in samo's crashlog contain 0x00000000 which mean NULL pointer access
